In [51]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop("species",axis=1)
y = df["species"]

In [9]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [26]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [27]:
model_knn.score(X_test,y_test)

0.98

In [42]:
from sklearn.svm import SVC
model_svm = SVC(gamma="auto")

In [38]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [39]:
model_svm.score(X_test,y_test)

0.98

In [40]:
#now let's use the grid search CV

In [41]:
from sklearn.model_selection import GridSearchCV

In [44]:
classifier = GridSearchCV((model_svm),{
    "C" : [1,10,20,30],
    "kernel" : ['rbf','linear']
},cv =5,return_train_score= False)

In [46]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [50]:
classifier.cv_results_

{'mean_fit_time': array([0.01513295, 0.00907173, 0.01064572, 0.0095881 , 0.01000042,
        0.0095973 , 0.00894008, 0.00803952]),
 'std_fit_time': array([0.00797947, 0.00098488, 0.00230126, 0.00103407, 0.00154838,
        0.00048833, 0.0006737 , 0.00087695]),
 'mean_score_time': array([0.01027222, 0.00712733, 0.00743456, 0.00640216, 0.00719848,
        0.00646458, 0.007061  , 0.00619559]),
 'std_score_time': array([0.00413384, 0.00068056, 0.00150568, 0.0004899 , 0.00074743,
        0.00045504, 0.00022099, 0.00117092]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [55]:
results = pd.DataFrame(classifier.cv_results_)

In [56]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015133,0.007979,0.010272,0.004134,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.009072,0.000985,0.007127,0.000681,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.010646,0.002301,0.007435,0.001506,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.009588,0.001034,0.006402,0.000490,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.010000,0.001548,0.007198,0.000747,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.009597,0.000488,0.006465,0.000455,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.008940,0.000674,0.007061,0.000221,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.008040,0.000877,0.006196,0.001171,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [57]:
results[["param_C",'param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      30          rbf         0.960000
7      30       linear         0.960000

In [59]:
from sklearn.model_selection import RandomizedSearchCV

In [60]:
classifier_r = RandomizedSearchCV((model_svm),{
    "C" : [1,10,20,30],
    "kernel" : ['rbf','linear']
},n_iter=4,cv =5,return_train_score= False)

In [61]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [64]:
results = pd.DataFrame(classifier_r.cv_results_)

In [66]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011102,0.006045,0.008467,0.002452,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.008601,0.001022,0.006797,0.000400,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
2,0.009712,0.000368,0.007655,0.000836,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
3,0.007380,0.001008,0.005328,0.000846,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [67]:
results[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      20       linear         0.966667
2      10       linear         0.973333
3      10          rbf         0.980000