In [2]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [10]:
#loading the diabetets dataset into a pandas data frames
loan_dataset= pd.read_csv('loan.csv')

In [11]:
loan_dataset.head() # used to show data structure of data file

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
0,32,Male,Engineer,Bachelor's,Married,85000,720,Approved
1,45,Female,Teacher,Master's,Single,62000,680,Approved
2,28,Male,Student,High School,Single,25000,590,Denied
3,51,Female,Manager,Bachelor's,Married,105000,780,Approved
4,36,Male,Accountant,Bachelor's,Married,75000,710,Approved

In [12]:
print(loan_dataset.shape)

(61, 8)

In [15]:
loan_dataset['loan_status'].value_counts() # it count number of diabetic patients and number of non diabetic patients

loan_status
Approved    45
Denied      16
Name: count, dtype: int64

In [56]:
# getting the statistical measure of the data
loan_dataset.describe()

             age         income  credit_score
count  61.000000      61.000000     61.000000
mean   37.081967   78983.606557    709.836066
std     8.424755   33772.025802     72.674888
min    24.000000   25000.000000    560.000000
25%    30.000000   52000.000000    650.000000
50%    36.000000   78000.000000    720.000000
75%    43.000000   98000.000000    770.000000
max    55.000000  180000.000000    830.000000

In [20]:
#loan_dataset.groupby('loan_status').mean()

In [29]:
loan_dataset.isnull().sum()

age                0
gender             0
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [30]:
#loan_dataset
loan_cat = loan_dataset.select_dtypes(include=['object']).copy()
loan_cat.head()

   gender  occupation education_level marital_status loan_status
0    Male    Engineer      Bachelor's        Married    Approved
1  Female     Teacher        Master's         Single    Approved
2    Male     Student     High School         Single      Denied
3  Female     Manager      Bachelor's        Married    Approved
4    Male  Accountant      Bachelor's        Married    Approved

In [34]:
loan_cat["occupation"].value_counts()

occupation
Engineer        5
Analyst         2
Chef            2
Writer          2
Banker          2
Receptionist    2
Teacher         2
Professor       2
Designer        2
Marketing       2
Salesman        2
Architect       2
Consultant      2
Doctor          2
IT              2
Artist          2
Lawyer          2
Nurse           2
Accountant      2
Manager         2
Photographer    1
Server          1
Psychologist    1
Software        1
Musician        1
Dentist         1
Programmer      1
Editor          1
Pilot           1
Realtor         1
Electrician     1
HR              1
Sales           1
Veterinarian    1
Researcher      1
Pharmacist      1
Student         1
Stylist         1
Name: count, dtype: int64

In [33]:
loan_cat["education_level"].value_counts()

education_level
Bachelor's     23
Master's       15
Doctoral       10
High School     7
Associate's     6
Name: count, dtype: int64

In [64]:
cat_loan = loan_dataset.copy()
cat_loan['gender'] = np.where(cat_loan['gender'].str.contains('Female'), 1, 0)
cat_loan['marital_status'] = np.where(cat_loan['marital_status'].str.contains('Single'), 1, 0)
cat_loan['loan_status'] = np.where(cat_loan['loan_status'].str.contains('Approved'), 1, 0)
#cat_loan['education_level'] = np.where(cat_loan['eductaion_level'].str.contains("Bachelor's"), 1,0)

cat_loan.sample(10)

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
6,42,0,Lawyer,Doctoral,0,120000,790,1
57,25,1,Receptionist,High School,1,32000,570,0
18,30,0,Researcher,Master's,1,72000,700,1
38,40,0,Software,Bachelor's,0,85000,740,1
27,43,1,HR,Master's,0,90000,750,1
22,46,0,Banker,Master's,0,115000,780,1
43,28,1,Nurse,Associate's,1,50000,660,0
26,35,0,Sales,Bachelor's,0,70000,700,1
45,36,1,Engineer,Master's,0,90000,740,1
1,45,1,Teacher,Master's,1,62000,680,1

In [66]:
# saperating the data and labels
X = cat_loan.drop(columns = ['loan_status','education_level','occupation'], axis = 1)
Y = cat_loan['loan_status']

In [67]:
Y.head()

0    1
1    1
2    0
3    1
4    1
Name: loan_status, dtype: int32

In [68]:
print(X)

    age  gender  marital_status  income  credit_score
0    32       0               0   85000           720
1    45       1               1   62000           680
2    28       0               1   25000           590
3    51       1               0  105000           780
4    36       0               0   75000           710
..  ...     ...             ...     ...           ...
56   39       0               0  100000           770
57   25       1               1   32000           570
58   43       0               0   95000           760
59   30       1               1   55000           650
60   38       0               0   65000           700

[61 rows x 5 columns]

In [69]:
print(Y)

0     1
1     1
2     0
3     1
4     1
     ..
56    1
57    0
58    1
59    1
60    1
Name: loan_status, Length: 61, dtype: int32

In [70]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [71]:
scaler.fit(X)

StandardScaler()

In [72]:
standardized_data = scaler.transform(X) # we can use directly scaler.fix_transform(X)

In [73]:
print(standardized_data)

[[-6.08224420e-01 -9.83738754e-01 -8.05387266e-01  1.79625673e-01
   1.41015475e-01]
 [ 9.47652887e-01  1.01653005e+00  1.24163870e+00 -5.07063209e-01
  -4.13948653e-01]
 [-1.08695590e+00 -9.83738754e-01  1.24163870e+00 -1.61173663e+00
  -1.66261794e+00]
 [ 1.66575011e+00  1.01653005e+00 -8.05387266e-01  7.76746440e-01
   9.73461669e-01]
 [-1.29492941e-01 -9.83738754e-01 -8.05387266e-01 -1.18934710e-01
   2.27444315e-03]
 [-1.56568738e+00  1.01653005e+00  1.24163870e+00 -9.25047746e-01
  -9.68912782e-01]
 [ 5.88604278e-01 -9.83738754e-01 -8.05387266e-01  1.22458702e+00
   1.11220270e+00]
 [-9.67273029e-01  1.01653005e+00  1.24163870e+00 -1.22360813e+00
  -1.24639485e+00]
 [-9.81007129e-03 -9.83738754e-01 -8.05387266e-01  3.88617942e-01
   5.57238572e-01]
 [ 1.30670150e+00  1.01653005e+00 -8.05387266e-01  3.01594932e+00
   1.52842580e+00]
 [ 2.14448158e+00 -9.83738754e-01 -8.05387266e-01  9.26026632e-01
   8.34720636e-01]
 [-7.27907290e-01  1.01653005e+00  1.24163870e+00 -3.27926979e-01
  -2.75207621e-01]
 [-1.32632164e+00 -9.83738754e-01  1.24163870e+00 -1.10418398e+00
  -1.38513588e+00]
 [ 2.29555668e-01  1.01653005e+00 -8.05387266e-01 -2.93665951e-02
   2.79756508e-01]
 [ 8.27970017e-01 -9.83738754e-01 -8.05387266e-01  4.78186057e-01
   6.95979604e-01]
 [-1.20663877e+00  1.01653005e+00  1.24163870e+00 -8.05623592e-01
  -8.30171750e-01]
 [-3.68858681e-01 -9.83738754e-01 -8.05387266e-01  2.69193788e-01
   4.18497540e-01]
 [ 4.68921408e-01  1.01653005e+00 -8.05387266e-01  1.37386721e+00
   1.25094373e+00]
 [-8.47590160e-01 -9.83738754e-01  1.24163870e+00 -2.08502825e-01
  -1.36466589e-01]
 [ 1.90511584e+00  1.01653005e+00 -8.05387266e-01  5.67754172e-01
   1.11220270e+00]
 [ 1.09872798e-01 -9.83738754e-01 -8.05387266e-01  3.03454816e-02
   1.41015475e-01]
 [-1.44600451e+00  1.01653005e+00  1.24163870e+00 -1.31317624e+00
  -1.80135898e+00]
 [ 1.06733576e+00 -9.83738754e-01 -8.05387266e-01  1.07530682e+00
   9.73461669e-01]
 [-4.88541550e-01  1.01653005e+00  1.24163870e+00 -1.01461586e+00
  -1.10765381e+00]
 [ 3.49238538e-01 -9.83738754e-01 -8.05387266e-01 -5.66775285e-01
  -2.75207621e-01]
 [-1.08695590e+00  1.01653005e+00  1.24163870e+00 -1.18934710e-01
   2.27444315e-03]
 [-2.49175811e-01 -9.83738754e-01 -8.05387266e-01 -2.68214902e-01
  -1.36466589e-01]
 [ 7.08287147e-01  1.01653005e+00 -8.05387266e-01  3.28905865e-01
   5.57238572e-01]
 [-7.27907290e-01 -9.83738754e-01  1.24163870e+00 -7.16055477e-01
  -5.52689686e-01]
 [ 1.42638437e+00  1.01653005e+00 -8.05387266e-01 -4.17495094e-01
   1.41015475e-01]
 [-1.20663877e+00 -9.83738754e-01  1.24163870e+00 -1.16389605e+00
  -1.52387691e+00]
 [ 2.02479871e+00  1.01653005e+00 -8.05387266e-01  1.79625673e-01
   6.95979604e-01]
 [-6.08224420e-01 -9.83738754e-01 -8.05387266e-01  4.78186057e-01
   9.73461669e-01]
 [ 1.18701863e+00  1.01653005e+00 -8.05387266e-01  1.82170778e+00
   1.38968477e+00]
 [-9.67273029e-01 -9.83738754e-01  1.24163870e+00 -1.46245644e+00
  -1.94010001e+00]
 [ 1.78543298e+00  1.01653005e+00 -8.05387266e-01  9.26026632e-01
   1.25094373e+00]
 [-2.49175811e-01 -9.83738754e-01 -8.05387266e-01  6.27466249e-01
   8.34720636e-01]
 [-1.32632164e+00  1.01653005e+00  1.24163870e+00 -1.52216851e+00
  -2.07884104e+00]
 [ 3.49238538e-01 -9.83738754e-01 -8.05387266e-01  1.79625673e-01
   4.18497540e-01]
 [-4.88541550e-01  1.01653005e+00  1.24163870e+00 -1.10418398e+00
  -1.24639485e+00]
 [ 1.09872798e-01 -9.83738754e-01 -8.05387266e-01  9.00575583e-02
   2.79756508e-01]
 [-8.47590160e-01  1.01653005e+00  1.24163870e+00 -6.26487362e-01
  -5.52689686e-01]
 [ 9.47652887e-01 -9.83738754e-01 -8.05387266e-01  9.26026632e-01
   1.11220270e+00]
 [-1.08695590e+00  1.01653005e+00  1.24163870e+00 -8.65335669e-01
  -6.91430718e-01]
 [ 5.88604278e-01 -9.83738754e-01 -8.05387266e-01  1.52314740e+00
   1.25094373e+00]
 [-1.29492941e-01  1.01653005e+00 -8.05387266e-01  3.28905865e-01
   4.18497540e-01]
 [-7.27907290e-01 -9.83738754e-01  1.24163870e+00 -4.17495094e-01
  -4.13948653e-01]
 [ 1.30670150e+00  1.01653005e+00 -8.05387266e-01  2.86666912e+00
   1.66716683e+00]
 [-3.68858681e-01 -9.83738754e-01 -8.05387266e-01 -2.93665951e-02
   1.41015475e-01]
 [-1.20663877e+00  1.01653005e+00  1.24163870e+00 -1.31317624e+00
  -1.52387691e+00]
 [ 4.68921408e-01 -9.83738754e-01 -8.05387266e-01  7.76746440e-01
   6.95979604e-01]
 [-9.67273029e-01  1.01653005e+00  1.24163870e+00 -9.25047746e-01
  -9.68912782e-01]
 [-9.81007129e-03 -9.83738754e-01 -8.05387266e-01  3.88617942e-01
   5.57238572e-01]
 [ 8.27970017e-01  1.01653005e+00 -8.05387266e-01  1.79625673e-01
   4.18497540e-01]
 [-6.08224420e-01 -9.83738754e-01  1.24163870e+00 -1.01461586e+00
  -1.10765381e+00]
 [ 1.54606724e+00  1.01653005e+00 -8.05387266e-01  1.22458702e+00
   1.38968477e+00]
 [ 2.29555668e-01 -9.83738754e-01 -8.05387266e-01  6.27466249e-01
   8.34720636e-01]
 [-1.44600451e+00  1.01653005e+00  1.24163870e+00 -1.40274436e+00
  -1.94010001e+00]
 [ 7.08287147e-01 -9.83738754e-01 -8.05387266e-01  4.78186057e-01
   6.95979604e-01]
 [-8.47590160e-01  1.01653005e+00  1.24163870e+00 -7.16055477e-01
  -8.30171750e-01]
 [ 1.09872798e-01 -9.83738754e-01 -8.05387266e-01 -4.17495094e-01
  -1.36466589e-01]]

In [75]:
X.head()

   age  gender  marital_status  income  credit_score
0   32       0               0   85000           720
1   45       1               1   62000           680
2   28       0               1   25000           590
3   51       1               0  105000           780
4   36       0               0   75000           710

In [97]:
X = standardized_data
Y = cat_loan['loan_status']

In [98]:
print(X)
print(Y)

[[-6.08224420e-01 -9.83738754e-01 -8.05387266e-01  1.79625673e-01
   1.41015475e-01]
 [ 9.47652887e-01  1.01653005e+00  1.24163870e+00 -5.07063209e-01
  -4.13948653e-01]
 [-1.08695590e+00 -9.83738754e-01  1.24163870e+00 -1.61173663e+00
  -1.66261794e+00]
 [ 1.66575011e+00  1.01653005e+00 -8.05387266e-01  7.76746440e-01
   9.73461669e-01]
 [-1.29492941e-01 -9.83738754e-01 -8.05387266e-01 -1.18934710e-01
   2.27444315e-03]
 [-1.56568738e+00  1.01653005e+00  1.24163870e+00 -9.25047746e-01
  -9.68912782e-01]
 [ 5.88604278e-01 -9.83738754e-01 -8.05387266e-01  1.22458702e+00
   1.11220270e+00]
 [-9.67273029e-01  1.01653005e+00  1.24163870e+00 -1.22360813e+00
  -1.24639485e+00]
 [-9.81007129e-03 -9.83738754e-01 -8.05387266e-01  3.88617942e-01
   5.57238572e-01]
 [ 1.30670150e+00  1.01653005e+00 -8.05387266e-01  3.01594932e+00
   1.52842580e+00]
 [ 2.14448158e+00 -9.83738754e-01 -8.05387266e-01  9.26026632e-01
   8.34720636e-01]
 [-7.27907290e-01  1.01653005e+00  1.24163870e+00 -3.27926979e-01
  -2.75207621e-01]
 [-1.32632164e+00 -9.83738754e-01  1.24163870e+00 -1.10418398e+00
  -1.38513588e+00]
 [ 2.29555668e-01  1.01653005e+00 -8.05387266e-01 -2.93665951e-02
   2.79756508e-01]
 [ 8.27970017e-01 -9.83738754e-01 -8.05387266e-01  4.78186057e-01
   6.95979604e-01]
 [-1.20663877e+00  1.01653005e+00  1.24163870e+00 -8.05623592e-01
  -8.30171750e-01]
 [-3.68858681e-01 -9.83738754e-01 -8.05387266e-01  2.69193788e-01
   4.18497540e-01]
 [ 4.68921408e-01  1.01653005e+00 -8.05387266e-01  1.37386721e+00
   1.25094373e+00]
 [-8.47590160e-01 -9.83738754e-01  1.24163870e+00 -2.08502825e-01
  -1.36466589e-01]
 [ 1.90511584e+00  1.01653005e+00 -8.05387266e-01  5.67754172e-01
   1.11220270e+00]
 [ 1.09872798e-01 -9.83738754e-01 -8.05387266e-01  3.03454816e-02
   1.41015475e-01]
 [-1.44600451e+00  1.01653005e+00  1.24163870e+00 -1.31317624e+00
  -1.80135898e+00]
 [ 1.06733576e+00 -9.83738754e-01 -8.05387266e-01  1.07530682e+00
   9.73461669e-01]
 [-4.88541550e-01  1.01653005e+00  1.24163870e+00 -1.01461586e+00
  -1.10765381e+00]
 [ 3.49238538e-01 -9.83738754e-01 -8.05387266e-01 -5.66775285e-01
  -2.75207621e-01]
 [-1.08695590e+00  1.01653005e+00  1.24163870e+00 -1.18934710e-01
   2.27444315e-03]
 [-2.49175811e-01 -9.83738754e-01 -8.05387266e-01 -2.68214902e-01
  -1.36466589e-01]
 [ 7.08287147e-01  1.01653005e+00 -8.05387266e-01  3.28905865e-01
   5.57238572e-01]
 [-7.27907290e-01 -9.83738754e-01  1.24163870e+00 -7.16055477e-01
  -5.52689686e-01]
 [ 1.42638437e+00  1.01653005e+00 -8.05387266e-01 -4.17495094e-01
   1.41015475e-01]
 [-1.20663877e+00 -9.83738754e-01  1.24163870e+00 -1.16389605e+00
  -1.52387691e+00]
 [ 2.02479871e+00  1.01653005e+00 -8.05387266e-01  1.79625673e-01
   6.95979604e-01]
 [-6.08224420e-01 -9.83738754e-01 -8.05387266e-01  4.78186057e-01
   9.73461669e-01]
 [ 1.18701863e+00  1.01653005e+00 -8.05387266e-01  1.82170778e+00
   1.38968477e+00]
 [-9.67273029e-01 -9.83738754e-01  1.24163870e+00 -1.46245644e+00
  -1.94010001e+00]
 [ 1.78543298e+00  1.01653005e+00 -8.05387266e-01  9.26026632e-01
   1.25094373e+00]
 [-2.49175811e-01 -9.83738754e-01 -8.05387266e-01  6.27466249e-01
   8.34720636e-01]
 [-1.32632164e+00  1.01653005e+00  1.24163870e+00 -1.52216851e+00
  -2.07884104e+00]
 [ 3.49238538e-01 -9.83738754e-01 -8.05387266e-01  1.79625673e-01
   4.18497540e-01]
 [-4.88541550e-01  1.01653005e+00  1.24163870e+00 -1.10418398e+00
  -1.24639485e+00]
 [ 1.09872798e-01 -9.83738754e-01 -8.05387266e-01  9.00575583e-02
   2.79756508e-01]
 [-8.47590160e-01  1.01653005e+00  1.24163870e+00 -6.26487362e-01
  -5.52689686e-01]
 [ 9.47652887e-01 -9.83738754e-01 -8.05387266e-01  9.26026632e-01
   1.11220270e+00]
 [-1.08695590e+00  1.01653005e+00  1.24163870e+00 -8.65335669e-01
  -6.91430718e-01]
 [ 5.88604278e-01 -9.83738754e-01 -8.05387266e-01  1.52314740e+00
   1.25094373e+00]
 [-1.29492941e-01  1.01653005e+00 -8.05387266e-01  3.28905865e-01
   4.18497540e-01]
 [-7.27907290e-01 -9.83738754e-01  1.24163870e+00 -4.17495094e-01
  -4.13948653e-01]
 [ 1.30670150e+00  1.01653005e+00 -8.05387266e-01  2.86666912e+00
   1.66716683e+00]
 [-3.68858681e-01 -9.83738754e-01 -8.05387266e-01 -2.93665951e-02
   1.41015475e-01]
 [-1.20663877e+00  1.01653005e+00  1.24163870e+00 -1.31317624e+00
  -1.52387691e+00]
 [ 4.68921408e-01 -9.83738754e-01 -8.05387266e-01  7.76746440e-01
   6.95979604e-01]
 [-9.67273029e-01  1.01653005e+00  1.24163870e+00 -9.25047746e-01
  -9.68912782e-01]
 [-9.81007129e-03 -9.83738754e-01 -8.05387266e-01  3.88617942e-01
   5.57238572e-01]
 [ 8.27970017e-01  1.01653005e+00 -8.05387266e-01  1.79625673e-01
   4.18497540e-01]
 [-6.08224420e-01 -9.83738754e-01  1.24163870e+00 -1.01461586e+00
  -1.10765381e+00]
 [ 1.54606724e+00  1.01653005e+00 -8.05387266e-01  1.22458702e+00
   1.38968477e+00]
 [ 2.29555668e-01 -9.83738754e-01 -8.05387266e-01  6.27466249e-01
   8.34720636e-01]
 [-1.44600451e+00  1.01653005e+00  1.24163870e+00 -1.40274436e+00
  -1.94010001e+00]
 [ 7.08287147e-01 -9.83738754e-01 -8.05387266e-01  4.78186057e-01
   6.95979604e-01]
 [-8.47590160e-01  1.01653005e+00  1.24163870e+00 -7.16055477e-01
  -8.30171750e-01]
 [ 1.09872798e-01 -9.83738754e-01 -8.05387266e-01 -4.17495094e-01
  -1.36466589e-01]]
0     1
1     1
2     0
3     1
4     1
     ..
56    1
57    0
58    1
59    1
60    1
Name: loan_status, Length: 61, dtype: int32

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [100]:
X_train,X_test,Y_train,Y_test =train_test_split(X,Y, test_size = 0.2,random_state=2) # test_Size 0.2 means testing data set is 20% and trainning dataset is 80%

In [101]:
print(X.shape, X_train.shape, X_test.shape) # total we have 768 data and we are using 614 number of data as a trainning data and 154 number of data as a testing data

(61, 5) (48, 5) (13, 5)

In [102]:
print(Y.shape, Y_train.shape, Y_test.shape)

(61,) (48,) (13,)

In [103]:
from sklearn.linear_model import LogisticRegression
# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [104]:

# Evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 100.00%

In [105]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [106]:
# evaluate the model
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))4

Confusion Matrix:
 [[ 2  0]
 [ 0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00        11

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13